/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "print.h"


void
morampudi_a2_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	a2_echo result_1;
	a2_echo  echo_1_arg;
	char entered_input[100];
	int i = 0;
#ifndef	DEBUG
	clnt = clnt_create (host, Morampudi_a2, a2Vers, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	while(i < 10){
	printf("\n");
	printf("enter the input: \n");
	scanf("%s", &entered_input);
	strcpy(echo_1_arg.input, entered_input);
	retval_1 = echo_1(&echo_1_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	else{
	printf("\n");
	printf("This is the result: %s \n", result_1.input);
	}	
	i++;
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	morampudi_a2_1 (host);
exit (0);
}
