/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PRINT_H_RPCGEN
#define _PRINT_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct a2_echo {
	char input[100];
};
typedef struct a2_echo a2_echo;

#define Morampudi_a2 0x456456
#define a2Vers 1

#if defined(__STDC__) || defined(__cplusplus)
#define Echo 1
extern  enum clnt_stat echo_1(a2_echo *, a2_echo *, CLIENT *);
extern  bool_t echo_1_svc(a2_echo *, a2_echo *, struct svc_req *);
extern int morampudi_a2_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Echo 1
extern  enum clnt_stat echo_1();
extern  bool_t echo_1_svc();
extern int morampudi_a2_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_a2_echo (XDR *, a2_echo*);

#else /* K&R C */
extern bool_t xdr_a2_echo ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PRINT_H_RPCGEN */
