/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "print.h"

bool_t
xdr_a2_echo (XDR *xdrs, a2_echo *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->input, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
