/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "print.h"

bool_t
echo_1_svc(a2_echo *argp, a2_echo *result, struct svc_req *rqstp)
{
	bool_t retval;

	/*
	 * insert server code here
	 */
	printf("Echo function called \n");
	printf("This is the input from the user: %s",argp->input);
	printf("\n");
	strcpy(result->input, argp->input);
	retval =1;
	return retval;
}

int
morampudi_a2_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
