/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PRINT_H_RPCGEN
#define _PRINT_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct a2_echo {
	char input[100];
};
typedef struct a2_echo a2_echo;

struct a2_sort {
	int count;
	int list[100];
	int sorted_list[100];
};
typedef struct a2_sort a2_sort;

struct a2_path {
	char pwd[100];
};
typedef struct a2_path a2_path;

struct a2_file_check {
	char files[100];
};
typedef struct a2_file_check a2_file_check;

struct a2_matrix_mul {
	int first[100];
	int second[100];
	int row_first;
	int col_first;
	int row_second;
	int col_second;
};
typedef struct a2_matrix_mul a2_matrix_mul;

#define Morampudi_a2 0x456456
#define a2Vers 1

#if defined(__STDC__) || defined(__cplusplus)
#define Echo 1
extern  enum clnt_stat echo_1(a2_echo *, a2_echo *, CLIENT *);
extern  bool_t echo_1_svc(a2_echo *, a2_echo *, struct svc_req *);
#define Sort 2
extern  enum clnt_stat sort_1(a2_sort *, a2_sort *, CLIENT *);
extern  bool_t sort_1_svc(a2_sort *, a2_sort *, struct svc_req *);
#define Path 3
extern  enum clnt_stat path_1(void *, a2_path *, CLIENT *);
extern  bool_t path_1_svc(void *, a2_path *, struct svc_req *);
#define File_Check 4
extern  enum clnt_stat file_check_1(a2_file_check *, a2_file_check *, CLIENT *);
extern  bool_t file_check_1_svc(a2_file_check *, a2_file_check *, struct svc_req *);
#define Matrix_mul 5
extern  enum clnt_stat matrix_mul_1(a2_matrix_mul *, a2_matrix_mul *, CLIENT *);
extern  bool_t matrix_mul_1_svc(a2_matrix_mul *, a2_matrix_mul *, struct svc_req *);
extern int morampudi_a2_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Echo 1
extern  enum clnt_stat echo_1();
extern  bool_t echo_1_svc();
#define Sort 2
extern  enum clnt_stat sort_1();
extern  bool_t sort_1_svc();
#define Path 3
extern  enum clnt_stat path_1();
extern  bool_t path_1_svc();
#define File_Check 4
extern  enum clnt_stat file_check_1();
extern  bool_t file_check_1_svc();
#define Matrix_mul 5
extern  enum clnt_stat matrix_mul_1();
extern  bool_t matrix_mul_1_svc();
extern int morampudi_a2_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_a2_echo (XDR *, a2_echo*);
extern  bool_t xdr_a2_sort (XDR *, a2_sort*);
extern  bool_t xdr_a2_path (XDR *, a2_path*);
extern  bool_t xdr_a2_file_check (XDR *, a2_file_check*);
extern  bool_t xdr_a2_matrix_mul (XDR *, a2_matrix_mul*);

#else /* K&R C */
extern bool_t xdr_a2_echo ();
extern bool_t xdr_a2_sort ();
extern bool_t xdr_a2_path ();
extern bool_t xdr_a2_file_check ();
extern bool_t xdr_a2_matrix_mul ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PRINT_H_RPCGEN */
