/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "print.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
echo_1(a2_echo *argp, a2_echo *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, Echo,
		(xdrproc_t) xdr_a2_echo, (caddr_t) argp,
		(xdrproc_t) xdr_a2_echo, (caddr_t) clnt_res,
		TIMEOUT));
}
